import { CountrySelectOption } from "@/components/ui/phone-input"

export const countries: CountrySelectOption[] = [
  { label: "Namibia", value: "NA" },
  { label: "South Africa", value: "ZA" },
  { label: "Zimbabwe", value: "ZW" },
  { label: "Algeria", value: "DZ" },
  { label: "Angola", value: "AO" },
  { label: "Benin", value: "BJ" },
  { label: "Botswana", value: "BW" },
  { label: "Burkina Faso", value: "BF" },
  { label: "Burundi", value: "BI" },
  { label: "Cameroon", value: "CM" },
  { label: "Cape Verde", value: "CV" },
  { label: "Central African Republic", value: "CF" },
  { label: "Chad", value: "TD" },
  { label: "Comoros", value: "KM" },
  { label: "Congo", value: "CG" },
  { label: "Democratic Republic of the Congo", value: "CD" },
  { label: "Djibouti", value: "DJ" },
  { label: "Egypt", value: "EG" },
  { label: "Equatorial Guinea", value: "GQ" },
  { label: "Eritrea", value: "ER" },
  { label: "Ethiopia", value: "ET" },
  { label: "Gabon", value: "GA" },
  { label: "Gambia", value: "GM" },
  { label: "Ghana", value: "GH" },
  { label: "Guinea", value: "GN" },
  { label: "Guinea-Bissau", value: "GW" },
  { label: "Ivory Coast", value: "CI" },
  { label: "Kenya", value: "KE" },
  { label: "Lesotho", value: "LS" },
  { label: "Liberia", value: "LR" },
  { label: "Libya", value: "LY" },
  { label: "Madagascar", value: "MG" },
  { label: "Malawi", value: "MW" },
  { label: "Mali", value: "ML" },
  { label: "Mauritania", value: "MR" },
  { label: "Mauritius", value: "MU" },
  { label: "Morocco", value: "MA" },
  { label: "Mozambique", value: "MZ" },
  { label: "Niger", value: "NE" },
  { label: "Nigeria", value: "NG" },
  { label: "Rwanda", value: "RW" },
  { label: "Sao Tome and Principe", value: "ST" },
  { label: "Senegal", value: "SN" },
  { label: "Seychelles", value: "SC" },
  { label: "Sierra Leone", value: "SL" },
  { label: "Somalia", value: "SO" },
  { label: "South Sudan", value: "SS" },
  { label: "Sudan", value: "SD" },
  { label: "Swaziland", value: "SZ" },
  { label: "Tanzania", value: "TZ" },
  { label: "Togo", value: "TG" },
  { label: "Tunisia", value: "TN" },
  { label: "Uganda", value: "UG" },
  { label: "Zambia", value: "ZM" },
]
